config/routes.rb
Rails.application.routes.draw do
 
  root 'welcome#index'
  resources :auftrags do
  resources :kommentars
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auftrag.rb
class Auftrag < ApplicationRecord
    has_many :kommentars, dependent: :destroy
     validates :title, presence: true,
                    length: { minimum: 5, maximum: 50 }
    
end

app/models/kommentar.rb
class Kommentar < ApplicationRecord
  belongs_to :auftrag
  validates :user, presence: true, length: {minimum: 3, maximum: 50}
  validates :body, presence: true, length: {minimum: 10, maximum: 300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/auftrags_controller.rb
class AuftragsController < ApplicationController
  before_action :set_auftrag, only: [:edit, :update, :show, :destroy]
  
  def index
    @auftrags = Auftrag.all
  end
  
  def show
  end
    
  def edit
  end

  def new
    @auftrag = Auftrag.new
  end
    
  def create
    @auftrag = Auftrag.new(auftrag_params)
    if @auftrag.save
      flash[:notice] ="Auftrags wurde erfolgreich erstellt"
      redirect_to @auftrag
    else
      render 'new'
    end
  end

  def update
    if @auftrag.update(auftrag_params)
      flash[:notice] = "Auftrag wurde erfolgreich geupdated"
      redirect_to @auftrag
    else
      render 'edit'
    end
  end
    
  def destroy
    @auftrag.destroy
    redirect_to auftrags_path
  end
    
    private
  def set_auftrag
  @auftrag = Auftrag.find(params[:id])
  end
  
  def auftrag_params
    params.require(:auftrag).permit(:title, :content)
  end
end

app/controllers/kommentars_controller.rb
class KommentarsController < ApplicationController
  def create
    @auftrag = Auftrag.find(params[:auftrag_id])
    @kommentar = @auftrag.kommentars.create(kommentar_params)
    redirect_to auftrag_path(@auftrag)
  end
  
  def destroy
    @auftrag = Auftrag.find(params[:auftrag_id])
    @kommentar = @auftrag.kommentars.find(params[:id])
    @kommentar.destroy
    redirect_to auftrag_path(@auftrag)
  end
 
  private
    def kommentar_params
      params.require(:kommentar).permit(:user, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auftrags_helper.rb
module AuftragsHelper
end

app/helpers/kommentars_helper.rb
module KommentarsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auftrags/_form.html.erb
<%= form_with(model: @auftrag, local: true) do |form| %>
 
  <% if @auftrag.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@auftrag.errors.count, "error") %> prohibited
        this auftrag from being saved:
      </h2>
      <ul>
        <% @auftrag.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 

app/views/auftrags/edit.html.erb
<h1>Artikel bearbeiten</h1>
 <%= render 'form' %>
 <%= link_to 'Back', auftrags_path %>

app/views/auftrags/index.html.erb
<h1>Aufräge listen</h1>

 <%= link_to 'Neuer Auftrag', new_auftrag_path %>
<table>
  <tr>
    <th>Titel</th>
    <th>Inhalt</th>
    <th></th>
  </tr>
 
  <% @auftrags.each do |auftrag| %>
    <tr>
      <td><%= auftrag.title %></td>
      <td><%= auftrag.content %></td>
      <td><%= link_to 'Show', auftrag_path(auftrag) %></td>
      <td><%= link_to 'Edit', edit_auftrag_path(auftrag) %></td>
       <td><%= link_to 'Destroy', auftrag_path(auftrag),
              method: :delete,
              data: { confirm: 'Sind sie sicher?' } %></td>
    </tr>
  <% end %>
</table>

app/views/auftrags/new.html.erb
<h1>Neuer Auftrag</h1>
<%= render 'form' %>
<%= link_to 'Back', auftrags_path %>

app/views/auftrags/show.html.erb
<p>
  <strong>Titel:</strong>
  <%= @auftrag.title %>
</p>
 
<p>
  <strong>Inhalt:</strong>
  <%= @auftrag.content %>
</p>

<h2>Kommentare</h2>
<%= render @auftrag.kommentars %>


<h2>Kommentieren:</h2>
<%= render 'kommentars/form' %>

<td><%= link_to 'Edit', edit_auftrag_path(@auftrag) %></td>
<%= link_to 'Back', auftrags_path %>

app/views/kommentars/_form.html.erb
<%= form_with(model: [ @auftrag, @auftrag.kommentars.build ], local: true) do |form| %>
  <p>
    <%= form.label :user %><br>
    <%= form.text_field :user %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/kommentars/_kommentar.html.erb
<p>
    <strong>User:</strong>
    <%= kommentar.user %>
  </p>
 
  <p>
    <strong>Kommentar:</strong>
    <%= kommentar.body %>
  </p>
  
  <p>
  <%= link_to 'Kommentar löschen', [kommentar.auftrag, kommentar],
               method: :delete,
               data: { confirm: 'Sind sie sicher?' } %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uebung3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to my rails app!</h1>
<%= link_to 'Meine App', controller: 'auftrags'%>